version: "3.8"

services:
  postgres:
    image: postgis/postgis:14-3.2-alpine
    container_name: dvf-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: dvf_user
      POSTGRES_PASSWORD: dvf_password
      POSTGRES_DB: dvf_data
      # PostgreSQL memory optimization for 2GB system (conservative)
      POSTGRES_SHARED_BUFFERS: "32MB"
      POSTGRES_EFFECTIVE_CACHE_SIZE: "128MB"
      POSTGRES_WORK_MEM: "1MB"
      POSTGRES_MAINTENANCE_WORK_MEM: "16MB"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dvf_user -d dvf_data"]
      interval: 10s
      timeout: 5s
      retries: 5
    # Optimized for 2GB total system RAM
    deploy:
      resources:
        limits:
          memory: 384M # Reduced for 2GB system
        reservations:
          memory: 192M
    command: >
      postgres 
      -c shared_buffers=32MB
      -c effective_cache_size=128MB
      -c work_mem=1MB
      -c maintenance_work_mem=16MB
      -c max_connections=20
      -c random_page_cost=1.1
      -c temp_buffers=8MB
      -c max_stack_depth=2MB

  dvf-importer:
    build:
      context: .
      dockerfile: Dockerfile.importer
    container_name: dvf-importer
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: dvf_user
      POSTGRES_PASSWORD: dvf_password
      POSTGRES_DB: dvf_data
      POSTGRES_PORT: "5432"
      DVF_START_YEAR: "${DVF_START_YEAR:-2020}"
      DVF_END_YEAR: "${DVF_END_YEAR:-2024}"
      DVF_CHUNK_SIZE: "${DVF_CHUNK_SIZE:-5000}"
      DVF_MAX_MEMORY: "${DVF_MAX_MEMORY:-128}"
    volumes:
      - ./logs:/app/logs
    restart: "no" # Run once and exit
    deploy:
      resources:
        limits:
          memory: 512M # Reduced for 2GB system
        reservations:
          memory: 256M

  flask-api:
    build:
      context: .
      dockerfile: Dockerfile.flask
    container_name: dvf-flask-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: dvf_user
      POSTGRES_PASSWORD: dvf_password
      POSTGRES_DB: dvf_data
      POSTGRES_PORT: "5432"
      FLASK_ENV: production
      PORT: "6644"
    ports:
      - "6644:6644"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6644/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 384M # Reduced for 2GB system
        reservations:
          memory: 192M

volumes:
  postgres_data:
